# !/usr/bin/env python3
# -*- coding:utf-8 -*-

# @Time    : 2026/07/08
# @Author  : contributor
# @FileName: summarization_processor.py

"""
Summarization document processor.

Recall post-processor that condenses a list of retrieved documents into a single
summary document, addressing the *summarization / 总结* direction of issue #248
("融合、过滤、摘要、总结...进一步提升多路召回后内容的质量").

Two operating modes are supported:

* **LLM mode** (``llm_name`` configured): an abstractive summary is generated by
  the referenced agentUniverse LLM component. This produces the highest-quality,
  query-aware summary and is the recommended mode for production use.
* **Extractive mode** (no ``llm_name``): a dependency-free fallback that scores
  the sentences of the concatenated documents by word frequency (boosted by
  query terms when a query is supplied) and keeps the top sentences in their
  original order. It is deterministic and works offline, which also makes the
  component fully unit-testable without an LLM.

The processor always returns a single :class:`Document` whose ``text`` is the
summary; its ``metadata`` records the operating mode and how many source
documents were summarized.
"""

import re
from typing import List, Optional, Dict, Any

from agentuniverse.agent.action.knowledge.doc_processor.doc_processor import DocProcessor
from agentuniverse.agent.action.knowledge.store.document import Document
from agentuniverse.agent.action.knowledge.store.query import Query
from agentuniverse.base.config.component_configer.component_configer import ComponentConfiger

# A small English stop-word list used to avoid over-weighting function words in
# the extractive scoring. Kept intentionally minimal and language-agnostic in
# spirit; CJK single characters are scored directly.
_STOP_WORDS = frozenset({
    "a", "an", "the", "and", "or", "but", "if", "then", "else", "when", "of",
    "to", "in", "on", "at", "by", "for", "with", "about", "as", "is", "are",
    "was", "were", "be", "been", "being", "this", "that", "these", "those",
    "it", "its", "from", "into", "than", "then", "so", "such", "not", "no",
    "can", "will", "just", "should", "would", "could", "may", "might", "i",
    "you", "he", "she", "we", "they", "them", "his", "her", "our", "their",
})

# Matches an ASCII/latin word OR a single CJK ideograph. Used both for frequency
# counting and for query-term overlap.
_WORD_RE = re.compile(r"[A-Za-z0-9]+|[一-鿿]")
# Sentence boundaries: latin terminal punctuation, CJK terminal punctuation,
# and newlines. Trailing empty fragments are dropped by the caller.
_SENTENCE_SPLIT_RE = re.compile(r"[。！？!?\.…]|\n+")

# Default system instruction for the LLM summarizer.
_DEFAULT_SUMMARY_INSTRUCTION = (
    "Summarize the following retrieved documents into a concise, coherent "
    "summary. Preserve the key facts and findings. Remove redundancy and "
    "irrelevant information."
)


class SummarizationProcessor(DocProcessor):
    """Recall post-processor that summarizes retrieved documents.

    Attributes:
        llm_name (Optional[str]): Name of the agentUniverse LLM component used
            for abstractive summarization. When ``None`` the processor falls
            back to deterministic extractive summarization.
        max_input_docs (int): Maximum number of source documents fed to the
            summarizer (documents beyond this count are dropped to bound the
            input size).
        max_sentences (int): Number of sentences kept by the extractive
            summarizer. Ignored in LLM mode.
        query_aware (bool): Whether the summary should be biased towards the
            query — extractive mode boosts sentences containing query terms,
            LLM mode asks the model to focus on the query.
        summary_instruction (str): Custom instruction prepended to the LLM
            prompt. Ignored in extractive mode.
        language (Optional[str]): Optional hint for the output language of the
            LLM summary (e.g. ``"Chinese"``). Ignored in extractive mode.
    """

    llm_name: Optional[str] = None
    max_input_docs: int = 10
    max_sentences: int = 5
    query_aware: bool = True
    summary_instruction: str = _DEFAULT_SUMMARY_INSTRUCTION
    language: Optional[str] = None

    def _process_docs(self, origin_docs: List[Document], query: Query = None) -> List[Document]:
        """Summarize the input documents into a single summary document.

        Args:
            origin_docs (List[Document]): Documents retrieved from the store.
            query (Query, optional): The origin query; used for query-aware
                summarization when ``query_aware`` is set.

        Returns:
            List[Document]: A one-element list containing the summary document.
            An empty input yields an empty list.
        """
        if not origin_docs or self.max_input_docs <= 0:
            return []

        # Bound the input size; recall results are typically relevance-ordered
        # so the leading documents are the most useful.
        source_docs = origin_docs[:self.max_input_docs]
        query_str = query.query_str if query else None

        joined_text = self._join_texts(source_docs)

        if self.llm_name:
            summary_text = self._llm_summarize(joined_text, query_str)
            mode = "llm"
        else:
            summary_text = self._extractive_summarize(joined_text, query_str)
            mode = "extractive"

        metadata: Dict[str, Any] = {
            "summarization_mode": mode,
            "source_doc_count": len(source_docs),
            "llm_name": self.llm_name,
        }
        # Carry over any existing metadata keys (e.g. knowledge source) from the
        # first document without clobbering our own keys.
        if source_docs[0].metadata:
            for k, v in source_docs[0].metadata.items():
                metadata.setdefault(k, v)

        return [Document(text=summary_text, metadata=metadata)]

    # ------------------------------------------------------------------ #
    # LLM mode
    # ------------------------------------------------------------------ #

    def _llm_summarize(self, text: str, query_str: Optional[str]) -> str:
        """Produce an abstractive summary via the configured LLM component."""
        if not text.strip():
            return ""
        llm = self._get_llm()
        instruction_lines = [self.summary_instruction]
        if self.language:
            instruction_lines.append(f"Write the summary in {self.language}.")
        if self.query_aware and query_str:
            instruction_lines.append(
                f"Focus on information relevant to the following query: \"{query_str}\".")
        prompt = "\n".join(instruction_lines) + "\n\nRetrieved documents:\n" + text
        messages = [
            {"role": "system",
             "content": "You are a helpful assistant that summarizes retrieved documents."},
            {"role": "user", "content": prompt},
        ]
        output = llm.call(messages=messages, streaming=False)
        # LLMOutput exposes ``.text`` for non-streaming results.
        return getattr(output, "text", "") or ""

    def _get_llm(self):
        """Resolve the referenced LLM component lazily to avoid import cycles."""
        from agentuniverse.llm.llm_manager import LLMManager
        llm = LLMManager().get_instance_obj(self.llm_name)
        if llm is None:
            raise ValueError(
                f"SummarizationProcessor: llm '{self.llm_name}' not found. "
                "Register the LLM component or switch to extractive mode "
                "(unset llm_name).")
        return llm

    # ------------------------------------------------------------------ #
    # Extractive mode
    # ------------------------------------------------------------------ #

    def _extractive_summarize(self, text: str, query_str: Optional[str]) -> str:
        """Produce a deterministic extractive summary.

        Sentences are scored by the summed frequency of their words (minus
        stop-words), length-normalized, and boosted by overlap with the query.
        The top ``max_sentences`` sentences are returned in their original
        order. Texts with fewer sentences than ``max_sentences`` are returned
        unchanged.
        """
        if not text.strip():
            return ""
        sentences = self._split_sentences(text)
        if len(sentences) <= self.max_sentences:
            return text.strip()

        tokenized = [self._tokenize(s) for s in sentences]
        word_freq = self._word_frequencies(tokenized)
        max_freq = max(word_freq.values()) if word_freq else 1.0
        query_terms = set(self._tokenize(query_str)) if (self.query_aware and query_str) else set()

        scored = []
        for idx, (sentence, tokens) in enumerate(zip(sentences, tokenized)):
            if not tokens:
                continue
            freq_score = sum(word_freq.get(w, 0) for w in tokens) / (len(tokens) ** 0.5)
            # Query relevance is scaled to the most frequent term so that a query
            # match can outweigh raw term frequency — otherwise frequent but
            # off-topic sentences always dominate the summary.
            overlap = sum(1 for w in tokens if w in query_terms)
            query_boost = 2.0 * max_freq * overlap
            scored.append((idx, sentence, freq_score + query_boost))

        # Keep the top-N highest-scoring sentences, then restore original order.
        top = sorted(scored, key=lambda x: x[2], reverse=True)[:self.max_sentences]
        top_in_order = sorted(top, key=lambda x: x[0])
        return " ".join(sentence for _, sentence, _ in top_in_order)

    @staticmethod
    def _join_texts(docs: List[Document]) -> str:
        """Concatenate document texts with a light separator, skipping empties."""
        parts = [d.text for d in docs if d.text]
        return "\n".join(parts)

    @staticmethod
    def _split_sentences(text: str) -> List[str]:
        """Split text into sentences on latin/CJK terminal punctuation.

        Delimiters are consumed; tiny fragments (< 2 chars after stripping) are
        dropped to avoid noise.
        """
        raw = _SENTENCE_SPLIT_RE.split(text)
        return [s.strip() for s in raw if s and len(s.strip()) >= 2]

    @staticmethod
    def _tokenize(text: str) -> List[str]:
        """Tokenize into lowercased latin words and individual CJK characters.

        Stop-words are removed so they do not dominate the frequency signal.
        """
        if not text:
            return []
        tokens = [m.group(0).lower() for m in _WORD_RE.finditer(text)]
        return [t for t in tokens if t not in _STOP_WORDS]

    @staticmethod
    def _word_frequencies(tokenized_sentences: List[List[str]]) -> Dict[str, int]:
        """Build a global word-frequency table across all tokenized sentences."""
        freq: Dict[str, int] = {}
        for tokens in tokenized_sentences:
            for w in tokens:
                freq[w] = freq.get(w, 0) + 1
        return freq

    # ------------------------------------------------------------------ #
    # Config
    # ------------------------------------------------------------------ #

    def _initialize_by_component_configer(self,
                                         doc_processor_configer: ComponentConfiger) -> 'SummarizationProcessor':
        """Initialize the processor parameters from the component configer.

        Args:
            doc_processor_configer (ComponentConfiger): Configuration object
                containing the summarization parameters.

        Returns:
            The initialized processor instance.
        """
        super()._initialize_by_component_configer(doc_processor_configer)
        if hasattr(doc_processor_configer, "llm_name"):
            self.llm_name = doc_processor_configer.llm_name
        if hasattr(doc_processor_configer, "max_input_docs"):
            self.max_input_docs = doc_processor_configer.max_input_docs
        if hasattr(doc_processor_configer, "max_sentences"):
            self.max_sentences = doc_processor_configer.max_sentences
        if hasattr(doc_processor_configer, "query_aware"):
            self.query_aware = doc_processor_configer.query_aware
        if hasattr(doc_processor_configer, "summary_instruction"):
            self.summary_instruction = doc_processor_configer.summary_instruction
        if hasattr(doc_processor_configer, "language"):
            self.language = doc_processor_configer.language
        return self
